### ISSUE TITLE
jinja2.exceptions.UndefinedError: '_' is undefined

### ISSUE THREAD

**Issue by jm33-m0** [getpelican/pelican-themes#507]
using the latest version of pelican and pelican-bootstrap3 theme, traceback is shown below:
```
CRITICAL: UndefinedError: '_' is undefined
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pelican/__init__.py", line 487, in main
    pelican.run()
  File "/usr/local/lib/python3.5/dist-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/usr/local/lib/python3.5/dist-packages/pelican/generators.py", line 600, in generate_output
    self.generate_pages(writer)
  File "/usr/local/lib/python3.5/dist-packages/pelican/generators.py", line 494, in generate_pages
    self.generate_articles(write)
  File "/usr/local/lib/python3.5/dist-packages/pelican/generators.py", line 372, in generate_articles
    blog=True)
  File "/usr/local/lib/python3.5/dist-packages/pelican/writers.py", line 230, in write_file
    override_output)
  File "/usr/local/lib/python3.5/dist-packages/pelican/writers.py", line 171, in _write_file
    output = template.render(localcontext)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/pelican/themes/pelican-bootstrap3/templates/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.5/dist-packages/pelican/themes/pelican-bootstrap3/templates/base.html", line 178, in top-level template code
    {% block content %}
  File "/usr/local/lib/python3.5/dist-packages/pelican/themes/pelican-bootstrap3/templates/article.html", line 77, in block "content"
    title="{{ _('Permalink to') }} {{ article.title|striptags }}">
jinja2.exceptions.UndefinedError: '_' is undefined
```

**Comment by jm33-m0** [comment]
after adding
```
PLUGIN_PATHS = ['path/to/plugins', ]
PLUGINS = ['i18n_subsites', ]
JINJA_ENVIRONMENT = {
    'extensions': ['jinja2.ext.i18n'],
}
```
to `pelicanconf.py`
and installing `python-gettext`, everything works

**Comment by jm33-m0** [comment]
i've used `pelican-bootstrap3` theme for almost a year, my fork becomes too outdated so.. this issue is quite new to me
hope my solution can help you guys

**Comment by jm33-m0** [comment]
https://github.com/getpelican/pelican-themes/issues/482
https://github.com/getpelican/pelican-themes/issues/460
