### ISSUE TITLE
Themes are failing to build for the new pelicanthemes.com domain

### ISSUE THREAD

**Issue by ployt0** [getpelican/pelican-themes#755]
50 themes are failing to build. I'd like to extend coverage to them:

![themes_failing_to_build](https://github.com/getpelican/pelican-themes/assets/25666053/48992fe9-7b6e-49d8-a9bb-22cd2f21942d)

Starting with these two:

![is_undefined_for_i18n_users](https://github.com/getpelican/pelican-themes/assets/25666053/7db9dfe2-747d-4acc-86a2-29a75be434f2)

Maybe the other faults are easier, but I've [proposed a PR for this one](https://github.com/getpelican/pelican-themes/pull/754). I couldn't automate installation of the i18n extension these themes demand, but I don't believe demonstrating extensions is in scope or required.

**Comment by ployt0** [comment]
It was a learning experience for me customising my local pull to generate more insights. It is very noisy to leave this in to run each time, on 50 failing cases. When passing becomes the expectation it would make more sense. I'm going to want to develop locally, not on Github Actions, so it isn't overly burdensome to generate leave in the line that does this.

Here's the stack trace for the `brick` theme:

```python
Traceback (most recent call last):
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\__init__.py", line 565, in main
    pelican.run()
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\__init__.py", line 128, in run
    p.generate_output(writer)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 704, in generate_output
    self.generate_pages(writer)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 606, in generate_pages
    self.generate_articles(write)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 475, in generate_articles
    write(article.save_as, self.get_template(article.template),
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\writers.py", line 269, in write_file
    _write_file(template, localcontext, self.output_path, name,
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\writers.py", line 202, in _write_file
    output = template.render(localcontext)
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\base.html", line 10, in top-level template code
    {% block head %}
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\base.html", line 26, in block 'head'
    <link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(category.slug) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME }} Categories Atom Feed" />
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\filters.py", line 1002, in do_format
    return soft_str(value) % (kwargs or args)
TypeError: not all arguments converted during string formatting
```

I know you didn't ask for it, but for the record, this, line 570, is the line to get the trace:

![print_traceback](https://github.com/getpelican/pelican-themes/assets/25666053/aa529c22-54b4-4cce-91ef-449fc8bc029a)

**Comment by ployt0** [comment]
It was a learning experience for me customising my local pull to generate more insights. It is very noisy to leave this in to run each time, on 50 failing cases. When passing becomes the expectation it would make more sense. I'm going to want to develop locally, not on Github Actions, so it isn't overly burdensome to leave in the line that does this.

Here's the stack trace for the `brick` theme:

```python
Traceback (most recent call last):
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\__init__.py", line 565, in main
    pelican.run()
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\__init__.py", line 128, in run
    p.generate_output(writer)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 704, in generate_output
    self.generate_pages(writer)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 606, in generate_pages
    self.generate_articles(write)
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\generators.py", line 475, in generate_articles
    write(article.save_as, self.get_template(article.template),
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\writers.py", line 269, in write_file
    _write_file(template, localcontext, self.output_path, name,
  File "C:\Users\ployt0\PycharmProjects\pelican\pelican\writers.py", line 202, in _write_file
    output = template.render(localcontext)
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\base.html", line 10, in top-level template code
    {% block head %}
  File "C:\Users\ployt0\PycharmProjects\pelican\_assets\bricks\templates\base.html", line 26, in block 'head'
    <link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(category.slug) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME }} Categories Atom Feed" />
  File "C:\Users\ployt0\PycharmProjects\pelican\venv\lib\site-packages\jinja2\filters.py", line 1002, in do_format
    return soft_str(value) % (kwargs or args)
TypeError: not all arguments converted during string formatting
```

I know you didn't ask for it, but for the record, this, line 570, is the line to get the trace:

![print_traceback](https://github.com/getpelican/pelican-themes/assets/25666053/aa529c22-54b4-4cce-91ef-449fc8bc029a)

**Comment by avaris** [comment]
> but I don't believe demonstrating extensions is in scope or required.

As the person who coded the preview generation, this is precisely why I didn't "fix" these issues. 

Some themes require plugins (`i18n`, `assets`, etc), some themes require certain variables to be defined and some are just broken and needs updates for the current `pelican`.

**Comment by ployt0** [comment]
> > but I don't believe demonstrating extensions is in scope or required.
> 
> As the person who coded the preview generation, this is precisely why I didn't "fix" these issues.

I can't tell if that is net praise or criticism for my PR. I don't suppose I will "fix" all the other issues, I just felt like opening an issue to give my PR more impetus.

I was interested in seeing pelican-bootstrap3 be run. I think it presents the most modern "bootstrap" theme. `brick` was just easy to type, and remember.

I know one theme, Flex, does accept the "_" sequence from i18n.

I wasn't sure what the job of the generator script was, other than to exercise the themes. I don't know what I was seeing but I wanted more of it.

If you know about "Argument error" I won't try to fix it.

**Comment by avaris** [comment]
> I can't tell if that is net praise or criticism for my PR. I don't suppose I will "fix" all the other issues, I just felt like opening an issue to give my PR more impetus.
> ...
> I wasn't sure what the job of the generator script was, other than to exercise the themes. I don't know what I was seeing but I wanted more of it.

Sorry, I realized I probably sound a bit crass. It was not aimed at you. Thanks for looking into and working on it.

I just don't think it's the right way, hence the quotes around the "fix". Sure, this script can do a lot more, workaround some issues of themes or even monkey-patch them so that they "work". But... First, this is not sustainable or maintainable. If a new theme is added with different requirements, it would need to be added to the list of workarounds. Second, this probably highlights an issue in the theme and would better be handled there (e.g. all the argument errors), rather than employing band-aids in the generation script. Third, a bit of criticism for the way themes are handled in `pelican`, which I'd gladly own :). Requirements, configuration etc could probably be a more smooth experience.

**Comment by ployt0** [comment]
My reading of this issue is that the output from `build-theme-preview` should be considered authoritative. Any theme failing to build is non-compliant, unmaintained, and should probably not be chosen for new projects.

The problem I had is that the themes are so old that `pelican-bootstrap3` was the most modern sounding one, particularly considering the prominence it gives `bootstrap` in its name. It sounds like *the* theme to use for bootstrap in Pelican.

I don't know, has bootstrap fallen out of favour, or is what we have here a lot of old, unmaintained themes? Apologies if that comes across as rude.

The reason I wanted to change `build-theme-preview` is that it is recent, looked like it could use help getting off the ground, and the PR wouldn't just languish unacknowledged, like it would on every other unmaintained repo.

I thought I'd explained I couldn't install the `i18n` extension the PR offers a workaround for. No? I guess it got lost in my edits.
